### PR TITLE
Remove unused dependencies

### PR DESCRIPTION
**Pull request by ghost**

### CODE REVIEW

**Comment by crossle** [comment]
Why remove the cryptography and crypto? some code import it.

**Comment by ghost** [comment]
> Why remove the cryptography and crypto? some code import it.

When it's removed, it still builds, tests pass and is able to be consumed - it's an extra compilation step that's not required. One of the other dependencies must be pulling it in?

**Comment by crossle** [comment]
Oh, no..Some warning

 * line 5, column 1 of lib/src/devices/DeviceConsistencyCommitment.dart: This package does not have crypto in the `dependencies` section of `pubspec.yaml`.
    ╷
  5 │ import 'package:crypto/crypto.dart';

**Comment by ghost** [comment]
Interesting - I'll take a look as to why it builds here...

**Comment by crossle** [comment]
GitHub builds ok...

**Comment by ghost** [comment]
> Oh, no..Some warning

So where are you seeing this?

**Comment by crossle** [comment]
The GitHub action only process ` pub run test`.  Should add `pub publish --dry-run`,  i run `pub publish --dry-run`

**Comment by ghost** [comment]
> The GitHub action only process ` pub run test`. Should add `pub publish --dry-run`, i run `pub publish --dry-run`


I've investigated your ```This package does not have crypto in the `dependencies` section of pubspec.yaml```...

This is what I did:
```
rm .pub-cache/hosted/pub.dartlang.org/*
pub get
pub run test
```

From the example app that consumes the _local_ `libsignal_protocol_dart` library :

```
flutter clean
flutter pub get
flutter test
flutter run
```

All works fine.

When I looked at inside `.pub-cache/hosted/pub.dartlang.org`, I can see the dependencies that were removed from the `pubspec.yaml` as part of this pull request

```
cryptography: ^1.4.1
crypto: ^2.1.5
```

So, what pulling in the `cryptography` and `crypto` dependencies?

Here's the answer...

1. [libsignal_protocol_dart/pubspec.yaml](https://github.com/MixinNetwork/libsignal_protocol_dart/blob/master/pubspec.yaml) references [ed25519_edwards/pubspec.yaml](https://github.com/Tougee/ed25519/blob/master/pubspec.yaml) 
1. [ed25519_edwards/pubspec.yaml](https://github.com/Tougee/ed25519/blob/master/pubspec.yaml) references [cryptography/pubspec.yaml](https://github.com/dint-dev/cryptography/blob/master/cryptography/pubspec.yaml)
1. [cryptography/pubspec.yaml](https://github.com/dint-dev/cryptography/blob/master/cryptography/pubspec.yaml) references [crypto/pubspec.yaml](https://github.com/dart-lang/crypto/blob/master/pubspec.yaml)

This can be confirmed by inspecting the _Install dependencies_ section of the [build](https://github.com/MixinNetwork/libsignal_protocol_dart/runs/1238312881?check_suite_focus=true) for this PR

BTW,  `dartx` is not used anywhere so can be removed.

So, I can conclude that the removal of these dependencies from this library does not prevent the app from being built/tested and consumed - only the publishing of it. 

The [error]( #707031917) that you experienced earlier is a separate issue and might be due to the version of `pub` that is being used. 

Did the failure occur while building on your local machine or on GitHub? I see that GitHub Actions is using the latest version of Dart (2.10.1).

Here's a link that might be related - https://github.com/dart-lang/pub/issues/2482#issuecomment-624664732

**Comment by ghost** [comment]
@crossle 
> Did the failure occur while building on your local machine or on GitHub? I see that GitHub Actions is using the latest version of Dart (2.10.1).

I've just updated `dart` (and therefore `pub`) to 2.10.1 and I get the same failure too when I run `pub publish --dry-run`

I'd be interested to hear anyone's comments on this - have I misunderstood something with regards to dependencies? 

For example, [ed25519_edwards/pubspec.yaml](https://github.com/Tougee/ed25519/blob/master/pubspec.yaml) doesn't include `crypto` in it's `pubspec.yaml` - what is @Tougee doing differently to get his library published?

**Comment by ghost** [comment]
I can see the logic behind `publish` requiring `crypto`, `cryptography` and `convert` to be included in the dependencies - as the library references them directly, relying on `ed25519_edwards` to pull them in is risky in case it decides to remove them in future releases. So, all good. However, there's there's no need to `dartx` so I'll create a new PR for the removal of that dependency - thanks for listening!

**Pull request merged**
